### PR TITLE
(Re)add direct messages for IRC and XMPP

### LINKED ISSUE #241: Fix/re-add direct messages
Disabled the initiation links in #227, but also not able to receive DMs anymore since that refactor.

Edit: actually, DMs still work fine for IRC, but receiving fails for XMPP.

### PR DESCRIPTION
**Pull request by raucao**
Also re-adds the ability to open URLs for channels that aren't currently joined.

For XMPP, the DM channel will be scoped to, and rendered under, the channel it belongs to, with an icon that indicates the scope. (We can improve channel titles/info etc. later on.)

Screenshot from 2021-08-28 13-42-40

closes #241, #126

### CODE REVIEW

File: app/routes/user_channel.js [hunk 1]
```diff
@@ -2,9 +2,17 @@ import BaseChannel from 'hyperchannel/routes/base_channel';
 
 export default BaseChannel.extend({
 
-  // FIXME must select acccount automatically
-  createChannelOrUserChannel: function(account, channelName){
-    return this.coms.createUserChannel(account, channelName);
+  createChannelOrUserChannel: function(account, channelId) {
+    let channel;
+    switch(account.protocol) {
```
Comment (silverbucket) [inline app/routes/user_channel.js:7]: Is there a way this could remain unified across protocols? What's the factor that makes it impossible at the moment and is it addressable?

Comment (raucao) [reply app/routes/user_channel.js:7]: That's not possible, because with IRC the direct message channel is to the username/nickname, whereas with XMPP, the channel DM is scoped to the channel (while there can also be an actual DM directly to the user).

**Review by galfert — APPROVED** [review]
Changes look ok to me and everything worked as expected.

In fact, this makes Hyperchannel even better than Beagle, because they don't even support channel DMs :)
