### PR TITLE
Fix userlist sorting

### LINKED ISSUE #140: Sort users in XMPP channel list
For some reason they're only sorted for IRC.

### LINKED ISSUE #146: Wrong user list sorting
Username lists in IRC channels are sorted separated by capitalization. All names that start with an uppercase letter show up first.

screen shot 2018-04-16 at 13 49 32

### PR DESCRIPTION
**Pull request by galfert**
Fixes #146 
Closes #140 

Sorts the usernames independent of capitalization and also fixes the missing sorting for XMPP channels.

### CODE REVIEW

**Comment by galfert** [comment]
The merge conflicts have been fixed.

File: tests/unit/models/base-channel-test.js [hunk 1]
```diff
@@ -70,6 +70,28 @@ module('Unit | Model | base-channel', function(hooks) {
...
   });
 
+  //
+  // sortedUserList
+  //
+
+  test('#sortedUserList returns an empty array if there are no users', function(assert) {
+    const channel = BaseChannel.create();
+
+    assert.equal(typeof channel.get('sortedUserList'), 'object');
```
Comment (skddc) [inline tests/unit/models/base-channel-test.js]: This would be true for any object, but you can check for an array using [`Array.isArray`](https://ecma-international.org/ecma-262/5.1/#sec-15.4.3.2).

File: tests/unit/models/base-channel-test.js [hunk 2]
```diff
@@ -70,6 +70,28 @@ module('Unit | Model | base-channel', function(hooks) {
...
+    assert.equal(channel.get('sortedUserList').length, 0);
+  });
+
+  test('#sortedUserList returns a list of sorted usernames', function(assert) {
+    const channel = BaseChannel.create();
+
+    channel.set('userList', ['silverbucket', 'XioNox', 'raucau', '@operator',
+                             'gregkare', 'galfert', '@MrOps']);
```
Comment (skddc) [inline tests/unit/models/base-channel-test.js]: I think we might also want to test other prefixes that are commonly used in IRC: http://www.geekshed.net/2009/10/nick-prefixes-explained/

**Comment by galfert** [comment]
I improved the test based on @skddc's comments  and added the other IRC name prefixes to the test as well.

**Comment by skddc** [comment]
Nice! :+1:
